theme: jekyll-theme-leap-day
title: Identified Suggested Collective Themes


Topic 1 - Paralysis

Topic 2 - Amputees & Prosthetics

Topic 3 - Motor Performance

Topic 4 - Balance

Topic 5 - Handwriting Development

Topic 6 - Speech

Topic 8 - Exercise & Learning

Topic 9 - Motor Pathways

Topic 10 - Shoulder Injuries

Topic 11 - Vocal Control

Topic 12 - Event-Related Potential

Topic 13 - Priming

Topic 14 - Transcranial Direct Current Stimulation (tDCS)

Topic 15 - Fitts's Law

Topic 16 - Reinforcement

Topic 17 - Spasticity

Topic 18 - Neuromuscular Electrical Stimulation (NME)

Topic 19 - Abdominal Control

Topic 20 - Motor Cortex

Topic 21 - Pelvic Control

Topic 22 - Congenital Disorders

Topic 23 - Soccer/Football/Rugby Players

Topic 24 - Eye Saccade

Topic 25 - Seizure

Topic 26 - Space Travel

Topic 27 - Learning

Topic 28 - Jumping

Topic 29 - Vascular Dementia

Topic 30 - Vestibular Disorders

Topic 31 - Swimming

Topic 32 - Gait

Topic 33 - Biofeedback

Topic 34 - Elderly Tai Chi

Topic 35 - Grasping

Topic 36 - Sway

Topic 37 - Dystonia

Topic 38 - Lumbar & Consciousness Control

Topic 39 - Prenatal Issues

Topic 40 - Mice

Topic 41 - Music

Topic 42 - Cerebellar Ataxia

Topic 43 - Visual-Motor Skills

Topic 44 - Tendon Vibration

Topic 45 - Attention Deficit Hyperactivity Disorder (ADHD)

Topic 46 - Motor Cortical Excitability

Topic 47 - Respiratory System

Topic 48 - Athletes

Topic 49 - Autism

Topic 50 - Methyl-CpG-binding protein-2 Gene

Topic 51 - Hand & Arm Coordination

Topic 52 - Pain

Topic 53 - Cycling

Topic 54 - Hoffmann Reflexes

Topic 55 - Rowing

Topic 56 - Surgical Skills

Topic 57 - Degrees of Freedom (DOF)

Topic 58 - Knee Injuries

Topic 59 - Arterial Flow

Topic 60 - Ballistic Tongues

Topic 61 - Fixation

Topic 62 - Leg tasks

Topic 63 - Pitch & Vocal Regulation via Auditory Feedback

Topic 64 - Bimanual

Topic 65 - Developmental Milestones

Topic 66 - Infant

Topic 67 - Motor Awareness

Topic 68 - Hearing Impairment

Topic 69 - Elderly

Topic 70 - Stroke

Topic 71 - Golf

Topic 72 - Motor Imagery & Mirror Therapy

Topic 73 - Stretching

Topic 74 - Drosophila

Topic 75 - Lumbar

Topic 76 - Neuron Firing

Topic 77 - Reading

Topic 78 - Stop-Signal Reaction

Topic 80 - Hand-Eye Coordination

Topic 81 - Implicit Motor Learning

Topic 82 - Body Ownership

Topic 83 - Ipsilateral Control

Topic 84 - Fundamental Movement Skills (FMS)

Topic 85 - Proprioception

Topic 86 - Feedback & Throwing Skills

Topic 87 - Feeding

Topic 88 - Huntington's Disease

Topic 89 - Motor Development in Twins

Topic 90 - Lifting Movements

Topic 91 - Calcium Channels

Topic 92 - Haptic Feedback

Topic 93 - Plasticity

Topic 94 - Orofacial Control

Topic 95 - Mutation

Topic 96 - Gamma Oscillations

Topic 97 - Purkinje Cells

Topic 98 - Games

Topic 100 - Deep Brain Stimulation (DBS)

Topic 101 - Uncertainty

Topic 102 - Handedness & Hormones

Topic 103 - Leg Control

Topic 105 - Motor Control Assessments

Topic 106 - Dopamine

Topic 107 - Sleep and Memory Consolidation

Topic 108 - Corpus Callosum

Topic 109 - Anticipatory Postural Adjustment (APA)

Topic 110 - Larynx

Topic 111 - Stuttering

Topic 112 - Dance

Topic 113 - Transplantation
